### ISSUE TITLE
pod not working for swift 3. 

### ISSUE THREAD

**Issue by poonamdhomane** [ios-studio/Typesetter#4]
pod not working for swift 3. Please update on this
[!] Unable to satisfy the following requirements:

- `Typesetter (~> 1.0.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Typesetter (~> 1.0.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by beatrichartz** [comment]
Thanks for raising this, it should be fixed now. Pod was not pushed.

**Comment by poonamdhomane** [comment]
Thanks a lot
